# Generated by Django 3.2.23 on 2023-12-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=256, unique=True, verbose_name='企业地址'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='企业名称'),
        ),
        migrations.AlterField(
            model_name='room',
            name='serial_number',
            field=models.CharField(max_length=512, unique=True, verbose_name='房间编号'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='deviceId',
            field=models.CharField(max_length=512, unique=True, verbose_name='设备编号'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='deviceSecret',
            field=models.CharField(max_length=512, unique=True, verbose_name='设备密钥'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='serial_number',
            field=models.CharField(max_length=512, unique=True, verbose_name='机器编号'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='区域名称'),
        ),
    ]
