# Generated by Django 4.0 on 2023-07-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='account',
        ),
    ]
