# Generated by Django 3.2.23 on 2024-01-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_unit_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.BooleanField(default=True, verbose_name='是否自动')),
                ('value', models.CharField(max_length=255, verbose_name='设置值')),
            ],
            options={
                'verbose_name': '机器设置',
                'db_table': 'unit_setting',
                'ordering': ('cmd',),
            },
        ),
        migrations.CreateModel(
            name='UnitSettingsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=64, verbose_name='指令名称')),
                ('desc_cn', models.CharField(max_length=64, verbose_name='中文解释')),
                ('desc_en', models.CharField(max_length=64, verbose_name='英文解释')),
                ('component', models.IntegerField(choices=[(1, 'slide'), (2, 'switch')], default=1, verbose_name='组件类型')),
                ('min_value', models.CharField(blank=True, max_length=8, null=True, verbose_name='最小值')),
                ('max_value', models.CharField(blank=True, max_length=8, null=True, verbose_name='最大值')),
                ('step', models.CharField(blank=True, max_length=8, null=True, verbose_name='调整区间')),
                ('unit_cn', models.CharField(blank=True, max_length=16, null=True, verbose_name='中文单位')),
                ('unit_en', models.CharField(blank=True, max_length=16, null=True, verbose_name='英文单位')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'APP参数设置',
                'db_table': 'unit_settings_list',
            },
        ),
        migrations.DeleteModel(
            name='AndroidSettings',
        ),
        migrations.AddField(
            model_name='unitsettings',
            name='cmd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_set', to='operations.unitsettingslist', verbose_name='设置名称'),
        ),
        migrations.AddField(
            model_name='unitsettings',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='operations.unit', verbose_name='设备名称'),
        ),
        migrations.AlterUniqueTogether(
            name='unitsettings',
            unique_together={('unit', 'cmd')},
        ),
    ]
