# Generated by Django 4.0 on 2023-07-10 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_company_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField(auto_now_add=True, verbose_name='检测时刻')),
                ('deviceId', models.CharField(max_length=512, verbose_name='机器实体编号')),
                ('deviceSecret', models.CharField(max_length=512, verbose_name='机器实体编号2')),
                ('json_val', models.JSONField(verbose_name='传感器值(json字典串)')),
            ],
            options={
                'verbose_name': '水肥传感器',
                'db_table': 'fertilizer',
            },
        ),
        migrations.CreateModel(
            name='PlantDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.IntegerField(default=1, verbose_name='作物周期')),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.plant', verbose_name='作物信息')),
            ],
            options={
                'verbose_name': '作物详情',
                'db_table': 'plant_desc',
            },
        ),
        migrations.CreateModel(
            name='RoomDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_val', models.JSONField(verbose_name='房间时刻详情')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.room', verbose_name='所属房间')),
            ],
            options={
                'verbose_name': '房间详情',
                'db_table': 'room_desc',
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField(auto_now_add=True, verbose_name='检测时刻')),
                ('deviceId', models.CharField(max_length=512, verbose_name='机器实体编号')),
                ('deviceSecret', models.CharField(max_length=512, verbose_name='机器实体编号2')),
                ('json_val', models.JSONField(verbose_name='传感器温度值(json列表串)')),
            ],
            options={
                'verbose_name': '温度传感器',
                'db_table': 'temperature',
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='components',
            field=models.JSONField(default=1, verbose_name='安卓端显示组件列表'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='deviceId',
            field=models.CharField(default=1, max_length=512, verbose_name='机器实体编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='deviceSecret',
            field=models.CharField(default=1, max_length=512, verbose_name='机器实体编号2'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.AddField(
            model_name='plantdesc',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.unit', verbose_name='所属机器'),
        ),
    ]
