# Generated by Django 3.2.23 on 2024-01-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20240112_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitSettings',
            new_name='UnitSetting',
        ),
    ]
