# Generated by Django 4.0 on 2023-07-10 13:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_fertilizer_plantdesc_roomdesc_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdesc',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='播种时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='status',
            field=models.IntegerField(choices=[(0, '禁用'), (1, '正常')], default=1, verbose_name='作物状态'),
        ),
        migrations.AlterField(
            model_name='plantdesc',
            name='plant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desc', to='operations.plant', verbose_name='作物信息'),
        ),
        migrations.AlterField(
            model_name='plantdesc',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plant_desc', to='operations.unit', verbose_name='所属机器'),
        ),
    ]
