# Generated by Django 3.2.23 on 2024-01-16 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_rename_unitsettings_unitsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitsettingslist',
            options={'ordering': ('id',), 'verbose_name': 'APP参数设置'},
        ),
        migrations.AddField(
            model_name='unitsettingslist',
            name='category_cn',
            field=models.IntegerField(blank=True, choices=[(1, '营养液及灌溉'), (2, '日夜周期'), (3, '气候控制'), (4, '光合作用'), (5, '系统设备')], null=True, verbose_name='中文分类'),
        ),
        migrations.AddField(
            model_name='unitsettingslist',
            name='category_en',
            field=models.IntegerField(blank=True, choices=[(1, 'Fertigation'), (2, 'Day-Night Cycle'), (3, 'Climate Control'), (4, 'Photosynthesis'), (5, 'System')], null=True, verbose_name='英文分类'),
        ),
        migrations.AlterField(
            model_name='plantdesc',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desc', to='operations.plant', verbose_name='作物算法信息'),
        ),
    ]
