# Generated by Django 4.0 on 2023-07-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_plantdesc_create_time_alter_plant_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdesc',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desc', to='operations.plant', verbose_name='作物信息'),
        ),
        migrations.AlterField(
            model_name='plantdesc',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_desc', to='operations.unit', verbose_name='所属机器'),
        ),
    ]
