# Generated by Django 4.0 on 2023-07-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_plantdesc_plant_alter_plantdesc_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='components',
            field=models.JSONField(blank=True, null=True, verbose_name='安卓端显示组件列表'),
        ),
    ]
