# Generated by Django 3.2.23 on 2024-02-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_algorithm_cultivar'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='cultivar',
            field=models.ManyToManyField(related_name='units', to='operations.Cultivar', verbose_name='该机器种植的品类'),
        ),
    ]
