# Generated by Django 4.0.2 on 2023-07-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_lighting_alter_unit_deviceid_alter_unit_devicesecret'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_control', models.JSONField(verbose_name='Phase Control')),
                ('automatic', models.IntegerField(default=50)),
                ('uvb', models.IntegerField(default=50)),
                ('uvc', models.BooleanField(default=True)),
                ('deep_blue', models.IntegerField(default=50)),
                ('main', models.IntegerField(default=50)),
                ('hyper_red', models.IntegerField(default=50)),
                ('far_red', models.IntegerField(default=50)),
            ],
            options={
                'verbose_name': '参数设置',
                'db_table': 'android_settings',
            },
        ),
    ]
