# Generated by Django 4.0 on 2023-09-07 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_androidsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet_type', models.CharField(default='action', max_length=64)),
                ('status', models.IntegerField(choices=[(1, 'activate'), (2, 'inactivate')], default=1)),
                ('type', models.IntegerField(choices=[(1, 'no_feedback'), (2, 'feedback')], default=1)),
                ('hardware', models.CharField(default='growLED', max_length=64)),
                ('environmental_factor', models.IntegerField(choices=[(1, 'temperature'), (2, 'humidity'), (3, 'CO2')], default=1)),
                ('instruction', models.IntegerField(choices=[(1, 'turn_on'), (2, 'turn_off'), (3, 'set_value')], default=1)),
                ('value', models.JSONField(blank=True, default=list, null=True)),
                ('curve', models.CharField(default='linear', max_length=64)),
                ('curve_duration', models.TimeField(blank=True, default='00:30:00', null=True)),
            ],
            options={
                'verbose_name': '第五层action',
                'db_table': 'action',
            },
        ),
        migrations.CreateModel(
            name='Cultivars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=64, verbose_name='英文名')),
                ('name_cn', models.CharField(max_length=64, verbose_name='中文名')),
                ('description_en', models.CharField(max_length=64, verbose_name='英文描述')),
                ('description_cn', models.CharField(max_length=64, verbose_name='中文描述')),
            ],
            options={
                'verbose_name': '第一层cultivars',
                'db_table': 'cultivars',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, verbose_name='key')),
                ('value', models.CharField(max_length=64, verbose_name='value')),
            ],
            options={
                'verbose_name': 'options',
                'db_table': 'environmental_options',
            },
        ),
        migrations.CreateModel(
            name='HardwareOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, verbose_name='key')),
                ('value', models.CharField(max_length=64, verbose_name='value')),
            ],
            options={
                'verbose_name': 'options',
                'db_table': 'hardware_options',
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=64, verbose_name='英文名')),
                ('name_cn', models.CharField(max_length=64, verbose_name='中文名')),
                ('description_en', models.CharField(max_length=64, verbose_name='英文描述')),
                ('description_cn', models.CharField(max_length=64, verbose_name='中文描述')),
                ('available_grow_objectives', models.JSONField(default=list, null=True)),
                ('available_grow_techniques', models.JSONField(default=list, null=True)),
                ('cultivars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='operations.cultivars', verbose_name='所属上层')),
            ],
            options={
                'verbose_name': '第二层models',
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='Phases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_index', models.IntegerField(default=0)),
                ('name_en', models.CharField(max_length=64, verbose_name='英文名')),
                ('name_cn', models.CharField(max_length=64, verbose_name='中文名')),
                ('description_en', models.CharField(max_length=64, verbose_name='英文描述')),
                ('description_cn', models.CharField(max_length=64, verbose_name='中文描述')),
                ('scheduled_events', models.JSONField(blank=True, default=list, null=True)),
                ('ending_condition', models.IntegerField(choices=[(1, 'any'), (2, 'all')], default=1, verbose_name='任何或所有')),
                ('ending_triggers', models.JSONField(blank=True, default=list, null=True)),
                ('f_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='operations.models', verbose_name='所属上层')),
            ],
            options={
                'verbose_name': '第三层phases',
                'db_table': 'phases',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=64, verbose_name='英文名')),
                ('name_cn', models.CharField(max_length=64, verbose_name='中文名')),
                ('description_en', models.CharField(max_length=64, verbose_name='英文描述')),
                ('description_cn', models.CharField(max_length=64, verbose_name='中文描述')),
            ],
            options={
                'verbose_name': '顶层species',
                'db_table': 'species',
            },
        ),
        migrations.CreateModel(
            name='Triggers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=64, verbose_name='英文名')),
                ('name_cn', models.CharField(max_length=64, verbose_name='中文名')),
                ('status', models.IntegerField(choices=[(1, 'activate'), (2, 'inactivate')], default=1)),
                ('triggered', models.BooleanField(default=False, verbose_name='布尔值')),
                ('type', models.IntegerField(choices=[(1, 'exception'), (2, 'trend'), (3, 'rate')], default=1)),
                ('operator', models.IntegerField(choices=[(1, 'greater_than'), (2, 'greater_than_or_equal_to'), (3, 'less_than'), (4, 'less_than_or_equal_to'), (5, 'not_equal_to')], default=1)),
                ('threshold', models.IntegerField(default=20)),
                ('direction', models.IntegerField(choices=[(1, 'increasing'), (2, 'decreasing'), (3, 'maintaining')], default=1)),
                ('timeframe', models.TimeField(blank=True, default='00:30:00', null=True)),
                ('toi', models.TimeField(blank=True, default='00:30:00', null=True)),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.environmentaloptions')),
                ('phases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='operations.phases', verbose_name='所属上级')),
            ],
            options={
                'verbose_name': '第六层triggers',
                'db_table': 'triggers',
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'activate'), (2, 'inactivate')], default=1)),
                ('type', models.IntegerField(choices=[(1, 'timed'), (2, 'interval')], default=1)),
                ('n_weeks', models.IntegerField(blank=True, null=True, verbose_name='每隔n周')),
                ('dow', models.JSONField(blank=True, default=list, null=True, verbose_name='事件发生在一周中的哪一天[]')),
                ('tod', models.TimeField(blank=True, default='08:00:00', null=True)),
                ('interval', models.TimeField(blank=True, default='00:30:00', null=True)),
                ('duration', models.TimeField(blank=True, default='16:00:00', null=True)),
                ('phases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='operations.phases', verbose_name='所属上层')),
            ],
            options={
                'verbose_name': '第四层instruction',
                'db_table': 'instruction',
            },
        ),
        migrations.AddField(
            model_name='cultivars',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivars', to='operations.species', verbose_name='所属上层'),
        ),
    ]
