# Generated by Django 3.2.23 on 2024-02-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_algorithm_choices_self'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='cultivar',
        ),
    ]
