# Generated by Django 3.2.23 on 2024-02-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_remove_unit_cultivar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdesc',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='plantdesc',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
        migrations.DeleteModel(
            name='PlantDesc',
        ),
    ]
