# Generated by Django 3.2.23 on 2024-02-08 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_auto_20240208_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPlantDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.JSONField(default=list, verbose_name='算法指令集')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='种植时间')),
                ('cultivar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.cultivar', verbose_name='种植品类')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_desc', to='operations.unit', verbose_name='设备')),
            ],
            options={
                'verbose_name': '作物详情',
                'db_table': 'unit_plant_desc',
            },
        ),
    ]
