# Generated by Django 4.0.2 on 2023-09-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_alter_phases_ending_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentaloptions',
            name='value',
            field=models.CharField(max_length=64, unique=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='triggers',
            name='direction',
            field=models.CharField(default='increasing', max_length=64),
        ),
        migrations.AlterField(
            model_name='triggers',
            name='metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.environmentaloptions', to_field='value'),
        ),
        migrations.AlterField(
            model_name='triggers',
            name='operator',
            field=models.CharField(default='greater_than', max_length=64),
        ),
        migrations.AlterField(
            model_name='triggers',
            name='status',
            field=models.CharField(default='active', max_length=64),
        ),
        migrations.AlterField(
            model_name='triggers',
            name='type',
            field=models.CharField(default='exception', max_length=64),
        ),
    ]
