# Generated by Django 4.0.2 on 2023-09-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_alter_environmentaloptions_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggers',
            name='direction',
            field=models.CharField(blank=True, default='increasing', max_length=64, null=True),
        ),
    ]
