# Generated by Django 3.2.23 on 2024-02-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_unitplantdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivar',
            name='cycle',
            field=models.IntegerField(default=1, verbose_name='种植周期'),
        ),
    ]
