# Generated by Django 4.0.2 on 2023-09-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_alter_triggers_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggers',
            name='direction',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='triggers',
            name='timeframe',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='triggers',
            name='toi',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
