# Generated by Django 4.0.2 on 2023-09-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_alter_triggers_direction_alter_triggers_timeframe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='environmental_factor',
            field=models.CharField(default='temperature', max_length=64),
        ),
        migrations.AlterField(
            model_name='action',
            name='instruction',
            field=models.CharField(default='turn_on', max_length=64),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(default='active', max_length=64),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(default='no_feedback', max_length=64),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='status',
            field=models.CharField(default='activate', max_length=64),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='type',
            field=models.CharField(default='timed', max_length=64),
        ),
    ]
