# Generated by Django 3.2.23 on 2024-02-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_alter_unitplantdesc_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='push',
            field=models.BooleanField(default=True, verbose_name='是否推送'),
        ),
    ]
