# Generated by Django 3.2.23 on 2024-03-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_algorithm_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='企业地址'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='企业邮箱'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_rep',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='企业法人'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tel',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='room',
            name='serial_number',
            field=models.CharField(max_length=255, verbose_name='房间编号'),
        ),
    ]
