# Generated by Django 4.0.2 on 2023-09-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_alter_action_environmental_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='interval',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='status',
            field=models.CharField(default='active', max_length=64),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='tod',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
