# Generated by Django 3.2.23 on 2024-03-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_auto_20240330_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='deviceId',
            field=models.CharField(max_length=255, unique=True, verbose_name='设备ID'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='deviceSecret',
            field=models.CharField(max_length=255, verbose_name='设备密钥'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='机器昵称'),
        ),
    ]
