# Generated by Django 3.2.23 on 2024-04-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_unit_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_cultivars',
            field=models.ManyToManyField(to='operations.Cultivar', verbose_name='允许种植的品类'),
        ),
    ]
