# Generated by Django 3.2.23 on 2024-05-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_unitplantdesc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='cmd',
            field=models.JSONField(default=dict, verbose_name='算法指令集'),
        ),
    ]
