# Generated by Django 3.2.23 on 2024-06-11 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_alter_algorithm_cmd'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCultivarAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.JSONField(default=dict, verbose_name='算法指令集')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.company', verbose_name='公司')),
                ('cultivar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.cultivar', verbose_name='种植品类')),
            ],
            options={
                'verbose_name': '公司品类算法',
                'db_table': 'company_cultivar_algorithm',
                'ordering': ('-id',),
            },
        ),
    ]
