# Generated by Django 3.2.23 on 2024-06-11 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_companycultivaralgorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycultivaralgorithm',
            name='algorithm',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_algorithm', to='operations.algorithm', verbose_name='对应算法'),
        ),
    ]
