# Generated by Django 3.2.23 on 2024-06-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_companycultivaralgorithm_algorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitsettingslist',
            name='cmd',
            field=models.CharField(max_length=64, unique=True, verbose_name='指令名称'),
        ),
    ]
