# Generated by Django 3.2.23 on 2024-06-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_unit_camera_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivar',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='cultivar',
            name='algorithm',
            field=models.ManyToManyField(to='operations.Algorithm', verbose_name='算法集默认值'),
        ),
    ]
