# Generated by Django 3.2.23 on 2024-02-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagequeuemodel',
            name='device_id',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagequeuemodel',
            name='content',
            field=models.JSONField(),
        ),
    ]
