# Generated by Django 4.0 on 2023-07-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=128, verbose_name='文件名')),
                ('file', models.ImageField(upload_to='upload/%Y/%m/%d', verbose_name='图片文件')),
            ],
            options={
                'verbose_name': '上传文件',
                'db_table': 'upload_file',
            },
        ),
    ]
