# Generated by Django 4.0 on 2023-07-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='文件名'),
        ),
    ]
