# Generated by Django 3.2.23 on 2023-12-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userqrcodeimg',
            options={'ordering': ['-id'], 'verbose_name': '用户二维码', 'verbose_name_plural': '用户二维码'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_super',
            field=models.BooleanField(default=False, verbose_name='超级管理员'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='isNaviLink',
            field=models.BooleanField(default=True, verbose_name='菜单'),
        ),
    ]
