# Generated by Django 4.0 on 2023-07-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useravatar',
            old_name='qr_code',
            new_name='qrcode',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='qrcode',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='用户二维码内容'),
        ),
    ]
