# Generated by Django 3.2.23 on 2024-01-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231231_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户')),
                ('role', models.CharField(max_length=32, verbose_name='角色')),
                ('table_name', models.CharField(max_length=32, verbose_name='表名')),
                ('command', models.IntegerField(choices=[(1, 'login'), (2, 'create'), (3, 'update'), (4, 'delete')], verbose_name='指令类型')),
                ('content', models.JSONField(blank=True, default='', null=True, verbose_name='日志内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '日志表',
                'verbose_name_plural': '日志表',
                'db_table': 'logs',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='language',
            field=models.IntegerField(choices=[(1, '中文'), (0, 'English')], default=1, verbose_name='cn/en'),
        ),
    ]
