# Generated by Django 4.0 on 2023-07-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_qr_code_useravatar_qrcode_userinfo_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='chinese',
            field=models.BooleanField(default=True, verbose_name='cn/en'),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='users/qrcode', verbose_name='用户二维码'),
        ),
    ]
