# Generated by Django 4.0 on 2023-07-04 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_company_account'),
        ('users', '0003_userinfo_chinese_alter_useravatar_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.company', verbose_name='所属企业'),
        ),
    ]
