# Generated by Django 3.2.23 on 2024-01-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240102_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='content',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='日志内容'),
        ),
    ]
