# Generated by Django 4.0 on 2023-07-06 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_company_account'),
        ('users', '0004_userinfo_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='chinese',
            field=models.IntegerField(choices=[(1, 'chinese'), (0, 'english')], default=1, verbose_name='cn/en'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='operations.company', verbose_name='所属企业'),
        ),
    ]
