# Generated by Django 4.0 on 2023-07-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userinfo_chinese_alter_userinfo_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='chinese',
            field=models.IntegerField(choices=[(1, 'Chinese'), (0, 'English')], default=1, verbose_name='cn/en'),
        ),
    ]
