# Generated by Django 3.2.23 on 2023-12-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessageToQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, verbose_name='设备id(动态队列前缀)')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('grow_cycle_id', models.CharField(max_length=100, verbose_name='增长周期id')),
                ('version', models.CharField(max_length=100, verbose_name='版本号')),
                ('data', models.JSONField(default=dict, verbose_name='数据')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Send Message To Queue',
                'verbose_name_plural': 'Send Message To Queue',
                'db_table': 'send_message_to_queue',
                'ordering': ['-create_time'],
            },
        ),
    ]
